# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobile
  pod 'GoogleSignIn', '4.1.1'



  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end